version: "3.7"

services:

  app_todos:
    image: mini_api
    ports:
      - 3000:90
  
  bd_todos:
    image: mysql:5.7
    volumes:
      - /home/julio/Desktop/bd-todo-backend/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todos
